# .streamlit/config.toml

[server]
headless = true
runOnSave = true

[theme]
primaryColor = "#6EB8FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
